export const DEFAULT_TAGS = {
    marriage_capable: [
        "befriend_krobus",
        "befriend_leah",
        "befriend_emily",
        "befriend_penny",
        "befriend_maru",
        "befriend_abigail",
        "befriend_haley",
        "befriend_alex",
        "befriend_elliott",
        "befriend_harvey",
        "befriend_sam",
        "befriend_sebastian",
        "befriend_shane",
    ],
    demetrius_fish: [
        "catch_a_flounder",
        "catch_a_halibut",
        "catch_a_largemouth_bass",
        "catch_a_sardine",
        "catch_a_sunfish",
        "catch_a_dorado",
        "catch_a_rainbow_trout",
        "catch_a_red_mullet",
        "catch_a_tilapia",
        "catch_a_tuna",
        "catch_an_albacore",
        "catch_a_midnight_carp",
        "catch_a_salmon",
        "catch_a_tiger_trout",
        "catch_a_lingcod",
        "catch_a_perch",
        "catch_a_squid",
    ],
};
