<template>
    <div class="pane-backdrop" :class="{ active: !!goal }"></div>
    <div class="pane" :class="{ active: !!goal }">
        <div class="header" v-if="goal">
            <template v-if="isNewGoal">New goal</template>
            <template v-else
                >Editing <code>{{ goal.id }}</code></template
            >
        </div>
        <form class="pane-content" v-if="goal" @submit.prevent="applyChanges">
            <template v-if="isNewGoal">
                <div class="row" v-if="isNewGoal">
                    <span>ID:</span>
                    <input
                        type="text"
                        v-model="goal.id"
                        minlength="3"
                        pattern="[a-z0-9_:]+"
                        :placeholder="goal.name == '' ? '<Autogenerated>' : defaultGoalID"
                    />
                </div>
                <div class="note">lowercase letters, numbers, _ and : only</div>
                <Panel type="warning" v-if="newIDIsInvalid">
                    Error:
                    <template v-if="goal.id">Goal ID is not unique.</template>
                    <template v-else>
                        Autogenerated goal ID would not be unique. Please change the goal name or
                        set an ID manually.
                    </template>
                </Panel>
            </template>

            <div class="row">
                <span>Name:</span>
                <input type="text" v-model="goal.name" required minlength="3" />
            </div>
            <div class="row">
                <span>Image URL:</span>
                <input type="url" v-model="goal.imageURL" placeholder="<none>" />
            </div>
            <div class="image-preview indent">
                <em>preview:</em>
                <img :src="goal.imageURL" alt="Icon preview" />
            </div>
            <div class="row">
                <span>Multiplicity:</span>
                <input type="number" v-model="goal.multiplicity" placeholder="1" min="1" max="99" />
            </div>
            <div class="note" v-if="reverseDeps[goal.id]?.size">
                Be careful when lowering the multiplicity, as having other goals' prerequisites be
                possible is only enforced when saving.
            </div>
            <div class="xp" v-if="goal">
                <div class="pad-edges">
                    <span>
                        Implied XP:
                        <template v-if="Object.keys(goal.xp).length == 0">&lt;none&gt;</template>
                    </span>
                    <PlainIconButton
                        icon="add"
                        title="Add an XP requirement"
                        @click="newXPVisible = !newXPVisible"
                        :disabled="isLevelGoal"
                    />
                </div>
                <div v-if="isLevelGoal">Level goals cannot have implied XP.</div>
                <form
                    @submit.prevent="addXPRequirement"
                    class="sub-form"
                    v-if="newXPVisible"
                    ref="newXPForm"
                >
                    <div class="row">
                        <label for="new-xp-skill">Skill:</label>
                        <select id="new-xp-skill" v-model="newXPSkill" required>
                            <option value="">No skill selected!</option>
                            <option :value="skill" v-for="skill in newXPEligibleSkills">
                                {{ skill }}
                            </option>
                        </select>
                    </div>
                    <div class="row">
                        <label for="new-xp-amount">Points of XP:</label>
                        <input
                            id="new-xp-amount"
                            type="text"
                            inputmode="numeric"
                            v-model.number="newXPAmount"
                            pattern="[1-9][0-9]*"
                            class="xp-amount"
                            required
                        />
                    </div>
                    <div class="row">
                        <AppButton icon="add" type="positive" small>Add</AppButton>
                        <AppButton icon="block" type="secondary" small @click="cancelXPForm"
                            >Cancel</AppButton
                        >
                    </div>
                </form>
                <ul>
                    <li v-for="(amount, skill) in goal.xp" class="xp-entry">
                        <span>{{ skill }}: {{ amount }}</span>
                        <PlainIconButton
                            icon="delete"
                            @click="deleteXPRequirement(skill)"
                            title="Delete XP requirement"
                        />
                    </li>
                </ul>
            </div>
            <div class="prerequisites" v-if="goal">
                <div class="first-line">
                    <template v-if="Object.keys(goal.prerequisites).length == 0">
                        <span>Prerequisites: &lt;none&gt;</span>
                        <PlainIconButton
                            icon="create_new_folder"
                            class="init-button"
                            title="Create prerequisite group"
                            @click="initPrerequisites"
                        />
                    </template>
                    <span v-else>Prerequisites:</span>
                </div>
                <ul
                    class="indent top-level"
                    v-if="Object.keys(goal.prerequisites).length > 0"
                    @click.prevent=""
                >
                    <li>
                        <TemplateEditorPrerequisites
                            :value="goal.prerequisites"
                            @update="handlePrerequisiteUpdate"
                            @delete="goal ? (goal.prerequisites = {}) : void 0"
                        />
                    </li>
                </ul>
            </div>
            <div class="row">
                <AppButton icon="save">Save</AppButton>
                <AppButton icon="block" type="secondary" @click.prevent="cancelEditing"
                    >Cancel</AppButton
                >
            </div>
        </form>
        <div class="pane-content centered" v-else>Nothing selected</div>
    </div>
</template>

<script setup lang="ts">
import { debounce } from "lodash-es";
import { currentEditedGoal } from "./template-editor-injects";
import { vInvalid } from "#imports";

defineExpose({ setBaseGoal, createNewGoal, cancelEditing });

const props = defineProps<{
    template: Template;
    goalsByID: Record<string, Goal>;
    reverseDeps: Record<string, Set<string>>;
}>();

const emit = defineEmits<{
    finishEditing: [goal: Goal];
    finishCreate: [goal: Goal];
}>();

// get the form
const form = ref<HTMLFormElement | null>(null);

// template-derived helpers
const skills = computed(() => {
    const result: Record<string, { goalIndex: number }> = {};
    for (let i = 0; i < props.template.goals.length; i++) {
        const goal = props.template.goals[i]!;
        if (goal.id.startsWith("level:")) {
            result[goal.id.slice("level:".length)] = { goalIndex: i };
        }
    }
    return result;
});

const goal = ref<Goal | null>(null);
// provide for deep-nested prerequisites component
provide(currentEditedGoal, goal);
const isNewGoal = ref(false);
const isLevelGoal = computed(() => goal.value?.id?.startsWith("level:") ?? false);

const debouncedImageURL = ref("");
const defaultGoalID = computed(() => {
    if (!goal.value) {
        return "";
    }

    const results = goal.value.name.match(/^Gain an? ([A-Za-z]+) Level$/i);
    if (results) {
        const [_fullMatch, skillName] = results;
        return `level:${skillName!.toLowerCase()}`;
    }

    return goal.value.name
        .trim()
        .replaceAll(" ", "_")
        .toLowerCase()
        .replaceAll(/[^a-z0-9_]+/g, "");
});
watch(
    () => goal.value?.imageURL,
    debounce(() => (debouncedImageURL.value = goal.value?.imageURL ?? ""), 300, {}),
);

const newIDIsInvalid = computed(() => {
    if (!isNewGoal.value) return false;

    // or instead of nullish coalescing to also rule out empty string
    const appliedGoalID = goal.value?.id || defaultGoalID.value;
    if (!appliedGoalID) return false;

    // !! to convert to boolean
    return !!props.goalsByID[appliedGoalID];
});

function setBaseGoal(newGoal: Goal) {
    // deep clone
    goal.value = JSON.parse(JSON.stringify(newGoal));
    isNewGoal.value = false;
}

function createNewGoal() {
    goal.value = {
        id: "",
        name: "",
        multiplicity: 1,
        imageURL: "",
        prerequisites: {},
        xp: {},
    };
    isNewGoal.value = true;
}

function applyChanges() {
    if (!goal.value) {
        return;
    }

    // this is not a form control invalid state, so check it separately
    if (newIDIsInvalid.value) {
        return;
    }

    // final tweaks
    if (!goal.value.imageURL) {
        delete goal.value.imageURL;
    }

    if (isNewGoal.value && goal.value.id == "") {
        goal.value.id = defaultGoalID.value;
    }

    // clone to get rid of reactivity
    if (isNewGoal.value) {
        emit("finishCreate", JSON.parse(JSON.stringify(goal.value)));
    } else {
        emit("finishEditing", JSON.parse(JSON.stringify(goal.value)));
    }
    goal.value = null;
}

function cancelEditing() {
    goal.value = null;
}

// editing actions

const newXPVisible = ref(false);
const newXPForm = ref<HTMLFormElement | null>(null);
const newXPSkill = ref<string>("");
const newXPAmount = ref<number | string>("");
const newXPEligibleSkills = computed(() => {
    if (!goal.value) {
        return skills.value;
    } else {
        return Object.keys(skills.value).filter((skill) => !(skill in goal.value!.xp));
    }
});
function deleteXPRequirement(skill: string) {
    delete goal.value!.xp[skill];
}
function addXPRequirement() {
    if (!goal.value || !newXPSkill.value || typeof newXPAmount.value == "string") {
        return;
    }

    goal.value.xp[newXPSkill.value] = newXPAmount.value;

    newXPSkill.value = "";
    newXPAmount.value = "";
    newXPVisible.value = false;
}
function cancelXPForm() {
    newXPSkill.value = "";
    newXPAmount.value = "";
    newXPVisible.value = false;
}

function initPrerequisites() {
    if (!goal.value) {
        return;
    }

    goal.value.prerequisites = { all: [] };
}

function handlePrerequisiteUpdate(newData: PrerequisiteGroup) {
    if (!goal.value) {
        return;
    }

    goal.value.prerequisites = newData;
}
</script>

<style scoped lang="scss">
@use "~/assets/base";

.pane {
    width: 400px;
    max-width: 90vw;

    background-color: var(--background-light);
    border-left: 2px solid var(--text-dim);

    max-height: 100%;
    display: flex;
    flex-flow: column nowrap;
}

.pane-content {
    padding: 1rem;
    flex-grow: 1;
    overflow-y: auto;
}

.pane-backdrop {
    display: none;
}

@media (max-width: 1000px) {
    .pane {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;

        transition: 0.5s ease transform;
        transform: translateX(100%);

        z-index: 11;
    }

    .pane.active {
        transform: translateX(0);
    }

    .pane-backdrop {
        display: block;
        position: fixed;
        z-index: 10;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        // do not block clicks by default
        pointer-events: none;

        background-color: black;
        opacity: 0;
        transition: 0.5s ease opacity;
    }

    .pane-backdrop.active {
        // block clicks when covering
        pointer-events: all;
        opacity: 0.3;
    }
}

.centered {
    text-align: center;
}

.pad-edges {
    display: flex;
    flex-flow: row nowrap;
    justify-content: space-between;
    align-items: center;
}

.header {
    padding: 1rem;
    background-color: base.$accent;
    color: whitesmoke;
}

.row input {
    width: 20em;
}

.row input[type="number"],
.row .xp-amount {
    width: 5em;
}

.indent {
    margin-left: 0.75em;
}

.sub-form {
    border: 2px dashed var(--text);
    border-radius: 4px;
    padding: 0.5rem;
}

.image-preview {
    * {
        vertical-align: middle;
    }
    img {
        margin-left: 0.5em;
        height: 1.5em;
    }
}

.xp {
    margin: 0.5rem 0;

    ul {
        margin: 0;
    }
}

.xp-entry {
    & > * {
        vertical-align: middle;
    }
}

.prerequisites {
    margin-bottom: 1rem;

    .first-line {
        display: flex;
        flex-flow: row nowrap;
        align-items: center;
    }
    .init-button {
        margin-left: 1rem;
    }

    .top-level {
        margin-block: 0;
        padding: 0;
        list-style-position: inside;
        overflow-x: auto;
    }
}
</style>
