import { convertNameToID } from "./utils.ts";

const fishing = {
    "Catch an Albacore": 35,
    "Catch an Anchovy": 25,
    "Catch a Blue Discus": 35,
    "Catch a Bream": 26,
    "Catch a Bullhead": 30,
    "Catch a Carp": 20,
    "Catch a Catfish": 40,
    "Catch a Chub": 26,
    "Catch a Dorado": 41,
    "Catch an Eel": 38,
    "Catch a Flounder": 31,
    "Catch a Ghostfish": 31,
    "Catch a Halibut": 31,
    "Catch a Herring": 23,
    "Catch an Ice Pip": 43,
    "Catch a Largemouth Bass": 31,
    "Catch a Lava Eel": 45,
    "Catch a Lingcod": 43,
    "Catch a Lionfish": 31,
    "Catch a Midnight Carp": 33,
    "Catch an Octopus": 46,
    "Catch a Perch": 26,
    "Catch a Pike": 35,
    "Catch a Pufferfish": 41,
    "Catch a Rainbow Trout": 30,
    "Catch a Red Mullet": 33,
    "Catch a Red Snapper": 28,
    "Catch a Salmon": 31,
    "Catch a Sandfish": 36,
    "Catch a Sardine": 25,
    "Catch a Scorpion Carp": 45,
    "Catch a Sea Cucumber": 28,
    "Catch a Shad": 30,
    "Catch a Slimejack": 33,
    "Catch a Smallmouth Bass": 24,
    "Catch a Squid": 40,
    "Catch a Stingray": 41,
    "Catch a Stonefish": 36,
    "Catch a Sturgeon": 41,
    "Catch a Sunfish": 25,
    "Catch a Super Cucumber": 41,
    "Catch a Tiger Trout": 35,
    "Catch a Tilapia": 31,
    "Catch a Tuna": 38,
    "Catch a Void Salmon": 41,
    "Catch a Walleye": 30,
    "Catch a Woodskip": 31,
    "Catch a Blobfish": 40,
    "Catch a Midnight Squid": 33,
    "Catch a Spook Fish": 35,
    "Catch the Angler": 215,
    "Catch the Crimsonfish": 230,
    "Catch the Glacierfish": 240,
    "Catch the Legend": 255,
    "Catch the Mutant Carp": 205,
    "Catch a Cockle": 5,
    "Catch a Crab": 5,
    "Catch a Crayfish": 5,
    "Catch a Lobster": 5,
    "Catch a Mussel": 5,
    "Catch an Oyster": 5,
    "Catch a Periwinkle": 5,
    "Catch a Shrimp": 5,
    "Catch a Snail": 5,
    "Catch Seaweed": 3,
    "Catch Green Algae": 3,
    "Catch White Algae": 3,
    "Craft Fiber Seeds": 60,
};
const combat = {
    "Slay 1000 Slimes": 10000,
    "Slay 150 Void Spirits": 3000,
    "Slay 200 Bats": 4400,
    "Slay 50 Skeletons": 400,
    "Slay 125 Cave Insects": 1250,
    "Slay 30 Duggies": 540,
    "Slay 500 Dust Sprites": 1000,
    "Slay 60 Rock Crabs": 1200,
    "Slay 100 Mummies": 2000,
    "Slay 50 Pepper Rex": 350,
    "Slay 250 Serpents": 5000,
    "Slay 150 Magma Sprites": 2550,
    "Craft a Geode Crusher": 1100,
};

function transformTable(table: Record<string, number>) {
    return Object.fromEntries(
        Object.entries(table).map(([goal, xp]) => [convertNameToID(goal), xp]),
    );
}

export const skills = [
    "farming",
    "mining",
    "foraging",
    "fishing",
    "combat",
] as const;
export type Skill = (typeof skills)[number];

export const goalXPValues: Record<Skill, Record<string, number>> = {
    farming: {},
    mining: {},
    foraging: {},
    fishing: transformTable(fishing),
    combat: transformTable(combat),
};
